language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "node"
  - "lts/*"
  - "7.6"
notifications:
  email: false
before_install:
  - npm i
before_script:
  - npm prune
script:
  - npm test
